# Generated by Django 5.0 on 2024-01-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to='static/dist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='static/dist'),
        ),
    ]
