# Generated by Django 5.0 on 2024-01-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0002_alter_book_book_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.TextField(),
        ),
    ]
