# Generated by Django 5.0 on 2024-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0004_book_description_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default=0, upload_to='static/dist'),
            preserve_default=False,
        ),
    ]
