# Generated by Django 5.0 on 2024-02-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0005_book_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
    ]
