# Generated by Django 5.0 on 2024-02-11 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0008_category_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio.category'),
        ),
    ]
