# Generated by Django 5.0 on 2024-02-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0010_alter_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='Genres',
        ),
    ]
