# Generated by Django 5.0 on 2024-02-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0011_rename_category_book_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='genre',
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name_plural': 'genres'},
        ),
    ]
