# Generated by Django 5.0 on 2024-02-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0012_rename_category_genre_alter_genre_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Genres',
        ),
        migrations.DeleteModel(
            name='genre',
        ),
    ]
