# Generated by Django 5.0 on 2024-02-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0016_remove_book_category_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Audio.category'),
            preserve_default=False,
        ),
    ]
