# Generated by Django 5.0 on 2024-02-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0018_alter_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
