# Generated by Django 5.0 on 2024-02-24 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0020_category_book_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ibrary_users',
            field=models.ManyToManyField(blank=True, related_name='library_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
