# Generated by Django 5.0 on 2024-02-25 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0023_book_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(default=[], related_name='library', to=settings.AUTH_USER_MODEL),
        ),
    ]
