# Generated by Django 5.0 on 2024-02-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0025_remove_book_users_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='add_to_library',
            field=models.BooleanField(default=False),
        ),
    ]
