# Generated by Django 5.0 on 2024-02-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0026_library_add_to_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
